Reduce matrix size

diff --git a/nestjs-crud/scripts/health_check b/nestjs-crud/scripts/health_check
--- a/nestjs-crud/scripts/health_check
+++ b/nestjs-crud/scripts/health_check
@@ -5,17 +5,21 @@ set -euo pipefail
 # Run the nestjs server in the background.
 npm run start:debug >> /dev/null &
 
-# Give the server enough time to be ready before accepting requests.
-# Dev server startup is slow!!!
-sleep 15
+# # Give the server enough time to be ready before accepting requests.
+# # Dev server startup is slow!!!
 
-# Run the healthcheck.
-if [[ $(curl -I http://localhost:3000/health-check 2>&1) =~ "200 OK" ]]; then
-   echo "Health check passed!"
-   exit 0
-else
-   echo "Health check failed!"
-   exit 1
-fi
+while true
+c=1
+do
+    # Run the healthcheck.
+    if [[ $(curl -I http://localhost:3000/health-check 2>&1) =~ "200 OK" ]]; then
+    echo "Health check passed!"
+    fi
+    exit 0
+    ((c++)) && ((c==20)) && break
+    curl -I http://localhost:3000/health-check
+    sleep 1
+done
 
-# Cleanup.
+echo "Health check failed!"
+exit 1
